### ISSUE TITLE
LORA point values from MQTT do not have math transformations applied

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/lora-raw#100]
The calculated `value` on the platform lora service does not match what is sent via MQTT.  

The `math-expression`, `scaling`, and `cov` should be applied to the `raw value` to get the `value`.  This seems to work.  However the `value` that is passed via MQTT still seems to be the `raw value` from the platform lora service. 

Value is converted from celcius to fahrenheit by math expression (this works):
![image](https://user-images.githubusercontent.com/40550860/115613599-effc1e80-a32f-11eb-9b15-e6cda754e20d.png)

value not sent as fahrenheit via MQTT:
![image](https://user-images.githubusercontent.com/40550860/115613692-13bf6480-a330-11eb-83ca-c46356ef5d38.png)
![image](https://user-images.githubusercontent.com/40550860/115613702-15892800-a330-11eb-9dce-37027cc67e63.png)

**Comment by NubeDev** [comment]
@RaiBnod 

I checked aswell and yes with MQTT we only get the decoded values over MQTT
