### ISSUE TITLE
CRITICAL! V1.7.4 DOESN'T RUN

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/lora-raw#136]
@RaiBnod  can you please look at this and see why it isn't running?

**Comment by CanuckMarc** [comment]
FYI: 1.7.3 works fine

**Comment by RaiBnod** [comment]
Maybe you have old `v1.7.4` which was broken. Can you please re-install it?

**Comment by CanuckMarc** [comment]
My bad, must have had the old 1.7.4 version installed.  Was on 2 controllers, so i throught it was widespread. Closed
