### ISSUE TITLE
Lora Sensor Names should allow spaces

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/lora-raw#74]
Currently the names of the LORA sensors do not allow names with spaces.  

Can we support names with spaces?

**Comment by NubeDev** [comment]
Its done like that for topics on MQTT

maybe we need to add a display name

**Comment by CanuckMarc** [comment]
maybe we can automatically convert spaces to underscores?   on import and when the user enters the name manually.

**Comment by RaiBnod** [comment]
Our convention for name: alphanumeric values with other characters `-` and `_` on all over the places.

We query from name sometimes, and having space becomes weird query API.

So, I wanna stick with current naming convention (don't wanna do magical backend operation: converting spaces to underscore util we must needed). It's showing proper message though.
