### ISSUE TITLE
MQTT persistance dosnt seem to be working

### ISSUE THREAD

**Issue by NubeDev** [NubeIO/lora-raw#91]
Also see https://github.com/NubeIO/rubix-wires/issues/1348

**Comment by CanuckMarc** [comment]
I'm reasonably certain that the `retain` flag is our issue.  This needs to be set for all messages that need to be retrieved on reboot, or re-subscribe.   

I tested all the other mosquitto configurations, and didn't have any success.

**Comment by RaiBnod** [comment]
In my local system, it's persisting the value when we have config `mqtt` > `retain: True`. See the video:

https://user-images.githubusercontent.com/6800775/115340466-7268cf00-a1c6-11eb-9bf8-a562d6210113.mov

**Comment by NubeDev** [comment]
@RaiBnod i can show you there is an issue

**Comment by RaiBnod** [comment]
@NubeDev and I debugged it and it's working fine.

It's may be related to the wires nodes issue. So, we can close this ticket.

**Comment by RaiBnod** [comment]
Old fixed issue, hence closing down this ticket.
